### ISSUE TITLE
two posibility for group implemetation

### ISSUE THREAD

**Issue by qPCR4vir** [qPCR4vir/nana-demo#1]
Hi, @cnjinhao 
First I show what I mean:
![group nana-wf](https://cloud.githubusercontent.com/assets/1911982/6544203/12f528e8-c545-11e4-9774-bd062deacc49.png)

I think people may expect a less invasive group. I have seen implementations which do nothing else but draw the border and the label, and anything else have to be done manually. This implementation manage all: creation, live (own) and layout. I think the best is something intermediary. The idea is you have some widgets (imput controls, label, etc.) which you want to manage normaly, but just visualy toghether because you have not decide to make a "class" or a formal union.
Hier are my old examples (C++ with windows forms).
Please see the new examples in:
https://github.com/qPCR4vir/nana-demo/blob/master/Examples/a_group_impl.cpp

https://msdn.microsoft.com/de-de/library/system.windows.forms.groupbox%28v=vs.110%29.aspx
Just Now

**Comment by cnjinhao** [comment]
Understood, I will start a new feature branch for the group.

**Comment by qPCR4vir** [comment]
Hi, @cnjinhao 
I see you are doing a lot with place, but for now I dont tested the thing.
I improved the idea, and now it look very like I need:
![group](https://cloud.githubusercontent.com/assets/1911982/6659262/ec51a156-cb81-11e4-96c9-103d42d2859f.png)
The new code is in the same place:
https://github.com/qPCR4vir/nana-demo/blob/master/Examples/a_group_impl.cpp

**Comment by qPCR4vir** [comment]
Oh! yes, and now there are 3 posibility, counting:
https://sourceforge.net/p/bowsimulationtool/code/260/tree//trunk/source/GUI/GroupBox.h
I think that taking the best from each it will be OK !

**Comment by qPCR4vir** [comment]
Hi, @cnjinhao 
Update with nested group:
![group-nested](https://cloud.githubusercontent.com/assets/1911982/6824029/5d77e57a-d2ee-11e4-96f2-e373daafb380.png)
from https://github.com/qPCR4vir/nana-demo/blob/master/Examples/a_group_impl.cpp

**Comment by cnjinhao** [comment]
Great! I have created a new feature branch for group called feature-group, would you please leave your real name for author information?

**Comment by qPCR4vir** [comment]
OK. Like in the email:
Ariel Vina-Rodriguez
(well, actually Ariel Viña Rodríguez, but for an easier internacionalization...)
By the way, your right name is Jin Hao? Jinhao? And cn is ?
