### ISSUE TITLE
error LNK2019 when call text_extent_size in vs2017

### ISSUE THREAD

**Issue by yinkaisheng** [qPCR4vir/nana-demo#18]
The solution complies without any errors.
However, if I add the following code
`                    std::string hw = "Hello, world!";
                    auto hw_size = graph.text_extent_size(hw);
`
to a_group_impl.cpp dw.draw, it can't compile successfully.
because nana.vcxproj has the option /std:c++latest, but other projects don't have /std:c++latest.
_nana_std_has_string_view is not defined without /std:c++latest.

**Comment by qPCR4vir** [comment]
Yes, sorry. I was updating... 
I will fix it today. 
You have to select all the projects and set the same option for all.

**Comment by yinkaisheng** [comment]
Thanks
