### ISSUE TITLE
Unhandled exception at 0x75A246D2 in file_explorer

### ISSUE THREAD

**Issue by ghost** [qPCR4vir/nana-demo#19]
Compilation is ok but two exceptions when debugging. 

![1](https://user-images.githubusercontent.com/25684578/115948771-b596ab00-a502-11eb-91e5-b0673989f1b7.PNG)

![2](https://user-images.githubusercontent.com/25684578/115948816-00b0be00-a503-11eb-86f3-316f106d1d40.PNG)

**Comment by cnjinhao** [comment]
Hi, @blackbeaf , change following line
https://github.com/qPCR4vir/nana-demo/blob/2a8d7da04abbbcb3e6afcd0a117e9dc17657335b/file_explorer.cpp#L102

into
```c++
std::error_code err;
if (fs::is_directory(item, err))
```
