### ISSUE TITLE
Missing filesystem_ext.hpp

### ISSUE THREAD

**Issue by steveking-gh** [qPCR4vir/nana-demo#7]
Building demos against the master branch of nana results in this error (Fedora 23, 64-bit, gcc 5.3):
file_explorer.cpp:23:46: fatal error: nana/filesystem/filesystem_ext.hpp: No such file or directory

nana version:
 7b6baa5      (origin/hotfix-1.3) Merge branch 'qPCR4vir-filesystem' into hotfix-1.3 (Jinhao)

Demos version
e198c1c        (HEAD -> dev_nana_in_examples, origin/dev_nana_in_examples, origin/dev_dir_it, dev_dir_it) fix UTF8 issue of calculator under VS2013 (Jinhao)

**Comment by qPCR4vir** [comment]
Oh, wonderful. I'm very, very happy you are testing the latest I'm playing with. 
I', trying to adapt and to make much more general the explorer thing. It compile and run now, but it is a protoversion. I will commit and push now to dev_nana_in_examples my latest version. Wait a minute.

**Comment by qPCR4vir** [comment]
Upps.. with the filesystem from microsoft it works, but not with our. 
https://travis-ci.org/qPCR4vir/nana/jobs/111620291
I will need to work on that. If you have boost::filesystem it will probably works.
That is why it is not yet include in the CMakefile in the jinhao nana repo. (it is pending)

**Comment by steveking-gh** [comment]
Hi qPCRvlr, Thanks for the quick response.  I pulled new nano-demo update and installed boost, but the same error occurs.

**Comment by qPCR4vir** [comment]
Hi,
I suspect you are not using cmake, or?
If not you will need to manually un comment 
https://github.com/qPCR4vir/nana/blob/hotfix-1.3/include/nana/config.hpp#L53

Or with cmake:
-DCMAKE_BOOST_FILESYSTEM_AVAILABLE=ON
or change to ON in:
https://github.com/qPCR4vir/nana/blob/hotfix-1.3/CMakeLists.txt#L34

**Comment by steveking-gh** [comment]
I'm using CMake.  

Switching nana to hotfix-1.3 branch solved the missing include, but filesystem_exp.hpp is a hot mess.  First error when building demos is:
nana/include/nana/filesystem/filesystem_ext.hpp:33:37: error: ‘experimental’ in namespace ‘std’ does not name a type

**Comment by qPCR4vir** [comment]
Hi, 
Could you make a fork of nana here? 
That will trigger a buid in travis and I will See exactly what is going on.  It works OK in all the configurations I tested.  What I need to fix is the configuration you  are  using.  We need to check where  is really boost filesystem. We will need to instal it in travis too.

**Comment by qPCR4vir** [comment]
Hi,
please make sure the options in lines 33-38 of CMakeList.txt are correct. I'm switching to make NANA_BOOST_FILESYSTEM_PREFERRED On by default. But this change will not be in jinhao repo now. It is in my repo. Anyway you need to set by self the correct values of lines 37 and 38 or make cmake find it automatically.

**Comment by qPCR4vir** [comment]
I added a log to boost config. But you will need to use:
https://github.com/qPCR4vir/nana/tree/hotfix-1.3

**Comment by steveking-gh** [comment]
I think the boost problem is solved. I had boost package installed, but the dependency is on boost-devel. Should you add find_package(boost) in the CMakeLists.txt file though?

**Comment by qPCR4vir** [comment]
Now it completely works in Linux and windows with VC2015 and gcc 5+, using boost or nana filesystem
https://travis-ci.org/qPCR4vir/nana/jobs/112151080

**Comment by qPCR4vir** [comment]
and now with gcc 4.9 !
https://travis-ci.org/qPCR4vir/nana/jobs/112157667
